kind: Deployment
apiVersion: apps/v1
metadata:
  name: gradio-hftgi-rag-faiss
  labels:
    app: gradio-hftgi-rag-faiss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-hftgi-rag-faiss
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gradio-hftgi-rag-faiss
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      affinity: {}
      terminationGracePeriodSeconds: 120
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: server
          livenessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 8
            periodSeconds: 100
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: APP_TITLE
              value: 'Talk with your documentation'
            - name: INFERENCE_SERVER_URL
              value: 'https://hf-tgi-llm-hosting.apps.rhods-internal.61tk.p1.openshiftapps.com/'
            - name: S3_ACCESS_KEY
              value: 'minio'
            - name: S3_SECRET_KEY
              value: 'minio123'
            - name: S3_URL
              value: 'https://minio-api-robert-tdoks.apps.rhods-internal.61tk.p1.openshiftapps.com'
            - name: S3_BUCKET
              value: 'documents'
            - name: MAX_NEW_TOKENS
              value: '512'
            - name: TOP_K
              value: '10'
            - name: TOP_P
              value: '0.95'
            - name: TYPICAL_P
              value: '0.95'
            - name: TEMPERATURE
              value: '0.01'
            - name: REPETITION_PENALTY
              value: '1.03'
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 24
          terminationMessagePolicy: File
          image: 'quay.io/rlundber/langchain-faiss:1.4'
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
